"""empty message

Revision ID: 6b71c4f37347
Revises: 
Create Date: 2018-10-13 10:10:29.695756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b71c4f37347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waypoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(precision=128), nullable=True),
    sa.Column('longitude', sa.Float(precision=128), nullable=True),
    sa.Column('altitude', sa.Float(precision=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waypoint_altitude'), 'waypoint', ['altitude'], unique=False)
    op.create_index(op.f('ix_waypoint_latitude'), 'waypoint', ['latitude'], unique=False)
    op.create_index(op.f('ix_waypoint_longitude'), 'waypoint', ['longitude'], unique=False)
    op.create_index(op.f('ix_waypoint_name'), 'waypoint', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waypoint_name'), table_name='waypoint')
    op.drop_index(op.f('ix_waypoint_longitude'), table_name='waypoint')
    op.drop_index(op.f('ix_waypoint_latitude'), table_name='waypoint')
    op.drop_index(op.f('ix_waypoint_altitude'), table_name='waypoint')
    op.drop_table('waypoint')
    # ### end Alembic commands ###
